// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.actionscript.ActionScript3Plugin from com.aramco.rcd.entity.common.LogonUser

package com.aramco.rcd.vo
{


  /** Java VO with XDOclet2 annotation for AS3 codegen. */

  [Bindable]
  [RemoteClass(alias="com.aramco.rcd.entity.common.LogonUser")]

  public class LogonUser extends BaseVO
  {


    public var userDivision:String;

    public var appAdmin:String;

    public var gocMember:String;

    public var userFullName:String;

    public var userCategory:String;

    public var userBadgeNo:String;

    public var userTeam:String;
	
	[Transient] public var userName:String;
	
	[Transient] public var orclPassword:String;
	
	[Transient] public var docPassword:String;


  }
}
