// Generated file. Do not edit.
// Generated by org.xdoclet.plugin.actionscript.ActionScript3Plugin from com.flexutil.shell.entity.BaseVO

package com.flexutil.shell.vo
{


  /** Java VO with XDOclet2 annotation for AS3 codegen. */

  [Bindable]
  [RemoteClass(alias="com.flexutil.shell.entity.BaseVO")]

  public class BaseVO
  {


    public var modified:Boolean;

    public var created:Boolean;

    public var updated:Boolean;

    public var deleted:Boolean;

    public var status:String;

    public var code:String;

    public var description:String;
	
	public var sortOrder:int;

  }
}
